# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Archive-Heritrix
version:      0.02
version_from: lib/Archive/Heritrix.pm
installdirs:  site
requires:
    Compress::Zlib:                0
    File::Find:                    0
    HTTP::Response:                0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
